[package]
name = "lix"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
evdev-rs = { version = "0.6", features = ["serde"] }
nix = "0.29"
serde_json = "1.0"
uinput = "0.1"
once_cell = "1.17"
